# Generated by Django 4.0 on 2021-12-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaccounts',
            name='balanc',
            field=models.IntegerField(default=0),
        ),
    ]
