# Generated by Django 4.0 on 2022-01-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0003_credicards_alter_newaccounts_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('subjet', models.TextField()),
                ('maile', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='credicards',
            new_name='creditcards',
        ),
    ]
