# Generated by Django 4.0 on 2022-01-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0005_feedback_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcards',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
