# Generated by Django 4.0 on 2022-01-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0006_creditcards_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(default='', null=True),
        ),
    ]
