# Generated by Django 4.0 on 2022-01-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0010_alter_feedback_message_alter_feedback_subjet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subjet',
            field=models.CharField(max_length=100),
        ),
    ]
